source: source
destination: site
markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:day/:title
url: http://vim.travisj.org
multiviews: true
sass: true
haml: true
post_defaults:
  layout: blog_post
